import { useEffect, useState } from 'react'
import { Plus, Power } from 'lucide-react'
import type { Teacher } from '@shared/types'
import { unwrap } from '../../lib/api'
import Modal from '../../components/Modal'
import Notice from '../../components/Notice'

export default function TeachersAdminPage(): JSX.Element {
  const [rows, setRows] = useState<Teacher[]>([])
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ username: '', code: '', namaGuru: '', jabatan: 'Guru' })
  const [notice, setNotice] = useState<{ message: string; type: 'success' | 'error' } | null>(null)
  const load = async (): Promise<void> => { try { setRows(unwrap<Teacher[]>(await window.api.admin.listTeachers())) } catch (e) { setNotice({ message: e instanceof Error ? e.message : 'Terjadi kesalahan.', type: 'error' }) } }
  useEffect(() => { void load() }, [])
  const save = async (): Promise<void> => { try { unwrap(await window.api.admin.createTeacher(form)); setOpen(false); setForm({ username: '', code: '', namaGuru: '', jabatan: 'Guru' }); await load(); setNotice({ message: 'Guru berhasil didaftarkan.', type: 'success' }) } catch (e) { setNotice({ message: e instanceof Error ? e.message : 'Gagal.', type: 'error' }) } }
  const toggle = async (id: number): Promise<void> => { try { unwrap(await window.api.admin.toggleTeacher(id)); await load() } catch (e) { setNotice({ message: e instanceof Error ? e.message : 'Terjadi kesalahan.', type: 'error' }) } }
  return <div className="space-y-6">{notice && <Notice {...notice} onClose={() => setNotice(null)} />}<div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold text-slate-900">Pendaftaran Guru</h2><p className="mt-1 text-sm text-slate-500">Kelola akun guru yang dapat menggunakan aplikasi.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} /> Daftarkan Guru</button></div><div className="card p-6"><div className="table-wrap max-h-[560px]"><table className="table-base"><thead><tr><th>No</th><th>Username</th><th>Nama Guru</th><th>Jabatan</th><th>Status</th><th className="text-right">Aksi</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}><td>{index + 1}</td><td className="font-mono text-xs">{row.username}</td><td className="font-semibold">{row.namaGuru}</td><td>{row.jabatan}</td><td><span className={`badge ${row.isActive ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{row.isActive ? 'Aktif' : 'Nonaktif'}</span></td><td className="text-right"><button onClick={() => toggle(row.id)} className={row.isActive ? 'text-rose-600' : 'text-emerald-600'}><Power size={16} /></button></td></tr>)}</tbody></table></div></div><Modal open={open} title="Daftarkan Guru" onClose={() => setOpen(false)} footer={<><button className="btn-secondary" onClick={() => setOpen(false)}>Batal</button><button className="btn-primary" onClick={save}>Simpan</button></>}><div className="space-y-4"><div><label className="label">Username</label><input className="field" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></div><div><label className="label">Kode Akses</label><input type="password" className="field" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></div><div><label className="label">Nama Guru</label><input className="field" value={form.namaGuru} onChange={(e) => setForm({ ...form, namaGuru: e.target.value })} /></div><div><label className="label">Jabatan</label><input className="field" value={form.jabatan} onChange={(e) => setForm({ ...form, jabatan: e.target.value })} /></div></div></Modal></div>
}
